//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emission
    {
        public int ID_Emission { get; set; }
        public Nullable<int> ID_Source { get; set; }
        public Nullable<double> count { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Source Source { get; set; }
    }
}
