//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class order2
    {
        public int id { get; set; }
        public Nullable<int> numTicket { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string C_from { get; set; }
        public string C_to { get; set; }
    }
}
